version: '3.8'

services:
  # 1. MySQL 데이터베이스
  veriq-db:
    image: mysql:8.0
    container_name: veriq-db
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: veriq_db
    volumes:
      - ./mysql_data:/var/lib/mysql

  # 2. Redis 캐시 서버
  veriq-redis:
    image: redis:latest
    container_name: veriq-redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

  # 3. Spring BE1 (Gateway - 박상민 )
  veriq-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAIN_CLASS=com.veriq.veriqgateway.VeriQGatewayApplication # 👈 Gateway 메인 지정
    container_name: veriq-be1
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: be1
      SERVER_PORT: 8081
      GOOGLE_RECAPTCHA_SECRET_KEY: ${GOOGLE_RECAPTCHA_SECRET_KEY}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      BE3_API_URL: "http://veriq-platform:8083/api/v1/scan/upload"

    depends_on:
      - veriq-db
      - veriq-redis

  # 4. Spring BE3 (Platform/Data Hub)
  veriq-platform:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAIN_CLASS=com.veriq.veriqbe3.VeriQBe3Application
    container_name: veriq-be3
    restart: always
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: be3
      SERVER_PORT: 8083
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    depends_on:
      - veriq-db
      - veriq-redis

  # 5. FastAPI (분석 엔진)
  veriq-analysis:
    build:
      context: ../analysis-engine
      dockerfile: Dockerfile
    container_name: veriq-analysis
    restart: always
    ports:
        - "8000:8000"
    depends_on:
        - veriq-db