server:
  port: 8083

spring:
  profiles:
    active: dev # 현재 활성화할 프로필
    include:
      - be1   # application-be1.yml 을 읽어옴
      - be3   # application-be3.yml 을 읽어옴
  datasource:
    url: jdbc:mysql://34.64.182.89/veriq_db?serverTimezone=Asia/Seoul
    username: root
    password: veriq123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB 연결을 최대 30초까지 기다려주는 인내심 설정
    hikari:
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # MySQL 8.0 버전에 맞게 Dialect를 조금 더 구체적으로 지정
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: veriq-redis
      port: 6379