# [공통 설정]
spring:
  profiles:
    active: gateway

---
# [Gateway 설정 구역 - BE1]
spring:
  config:
    activate:
      on-profile: gateway

server:
  port: 8081

be3:
  api:
    url: http://veriq-be3:8083

google:
  recaptcha:
    secret-key: ${GOOGLE_RECAPTCHA_SECRET_KEY:6LcFLIssAAAAAPFDzhaixpw0fnxyQW-ieQS8O8TD}

---
# [BE3 설정 구역 - 나]
spring:
  config:
    activate:
      on-profile: be3
  # 데이터베이스 및 JPA 설정을 하나의 spring: 블록 아래로 모았습니다.
  datasource:
    url: jdbc:mysql://veriq-db:3306/veriq_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083