server:
  port:  8081


spring:
  datasource:
    # url 끝에 allowPublicKeyRetrieval=true 를 추가했습니다.
    url: jdbc:mysql://localhost:3306/veriq?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: sangmin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # 최신 버전에서는 Dialect를 명시하지 않아도 자동으로 잡히지만, 명시하려면 최신 버전에 맞게 두는 것이 좋습니다.
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379
