name: Veri-Q Auto Deploy

on:
  push:
    branches: [ "develop" ] # develop 브랜치 푸시 시 자동 배포

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /home/sk38808738
            sudo docker-compose pull # 최신 이미지 다운로드
            sudo docker-compose up -d # 컨테이너 재실행